name: First Workflow
on: [push]

job:
 run-shell-command:
  run-on: ubuntu-latest
  steps:
   - name: echo a string
     run: echo "Hello World"
   - name: Multiple Command
     run: |
       node -v
       npm -v
       
